### ISSUE TITLE
 extract from ID case the ID files

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [waldronlab/TCGAutils#10]
I want create a manifest file where I have my UIDD from case and UIDD from Files.

How can do this?

**Comment by LiNk-NY** [comment]
If you're talking about the `GenomicDataCommons::manifest` function, you can create the manifest first and then run `TCGAutils::UUIDtoUUID` to get the identifiers that are missing. You can then merge the two `data.frame`s.

**Comment by bioinfo-dirty-jobs** [comment]
thanks for the hep @LiNk-NY 
I have tried this but not works. I have bcuidd and I want file id
```
UUIDtoUUID(tolower('F94615EA-551C-4F63-AF0D-5E49C87FC66E'))
[1] file_id       cases.case_id

```

**Comment by LiNk-NY** [comment]
This will work. Please provide a `to_type` argument here. 
```
UUIDtoUUID(tolower("F94615EA-551C-4F63-AF0D-5E49C87FC66E"), to_type = "file_id")
```
