### ISSUE TITLE
Error if UUIDs from Copy Number File

### ISSUE THREAD

**Issue by DarioS** [waldronlab/TCGAutils#23]
I downloaded the file named HNSC.focal_score_by_genes.txt from Genomic Data Commons and the column headings are some kind of UUID. I tried both options of `from_type` and got the same error. A minimal example is

```r
UUIDtoBarcode("f8c7d038-1182-42d0-8787-b84b5ca57eaf")
Error in names(rframe) <- c(from_type, APIendpoint) : 
  'names' attribute [2] must be the same length as the vector [0]
```

I am not sure if this is a TCGA problem or a TCGAutils problem. I also downloaded the MAF for this patient cohort and used `readLines` to import it into R. I then used `grep` with option `fixed = TRUE` to search for each of the UUIDs anywhere in the MAF lines and none of the UUID matched any text in the MAF. In any case, the error message could be nicer-looking and user-informative if there was some kind of `tryCatch` used to provide a clearer error.

**Comment by LiNk-NY** [comment]
Hi Dario, @DarioS 

Thanks for your report. 
The UUID entered is an aliquot UUID with a barcode of `TCGA-UF-A71A-06A-11D-A390-01`.
Currently, only case and file UUIDs are supported. 

I will add a more informative error.

Best,
Marcel

**Comment by LiNk-NY** [comment]
See 4c3e1e45bbeeedbebdcc47d9c227db5fb8b6c625
