### ISSUE TITLE
UUIDtoBarcode returning subset of output

### ISSUE THREAD

**Issue by LiNk-NY** [waldronlab/TCGAutils#24]
https://support.bioconductor.org/p/122806/#125810
> Hi, thank you very much for this library.
>
> I seem to have noticed a mismatch on some UUID when converting from file_id. For example, '56467ebd-af89-4413-84b5-1e00699a2744' returns 'TCGA-2L-AAQM-01A-11D-A396-01' but the GDC portal returns 'TCGA-IB-A5SO' instead. I am converting the masked copy number segment data and I noticed that a number of these mismatch comes from those cases with multiple aliquots. Could you confirm this or perhaps I have done something wrong?
>
> My code is simply: UUIDtoBarcode('56467ebd-af89-4413-84b5-1e00699a2744', fromtype = "fileid")
>
> Thank you in advance.

**Comment by tiagochst** [comment]
The UUID points to a file with multiple barcodes.
![Screenshot at 09-41-13](https://user-images.githubusercontent.com/145529/67407513-9aea1b80-f585-11e9-879a-d6360f1f7805.png)
