### ISSUE TITLE
Inquiry Regarding TCGA Barcode Identification with TCGAutils

### ISSUE THREAD

**Issue by Sarigenes** [waldronlab/TCGAutils#34]
**Issue Description:**
Struggling with identifying TCGA barcodes for samples in a manifest file downloaded from the 2020 GDC Data Portal. This is crucial for distinguishing between tumor and normal samples.

**Steps Taken:**
Attempted "UUID to TCGA barcode" function from TCGAutils, resulting in "See help("GDC-defunct")" error.
Tried 'UUIDhistory', which only provided version information without updates (see below).

**Current Situation:**
Uncertain how to obtain TCGA barcodes for accurate sample classification from the manifest file.

**Request for Assistance:**
Seeking guidance on efficiently identifying TCGA barcodes for samples in the manifest file.

**Additional Information with Manifest File:**
Download Date: 2020
Code used:
```
uuids <- c("11b29aeb-57c7-48dd-b2fc-3190d4ea4d39",
           "15c6062d-ae1e-4d9b-ba92-11faad1f727a")

UUIDtoBarcode(uuids, from_type = "file_id")
```
Output:
```
The 'legacy' argument is defunct.
See help("GDC-defunct")
```
Code used: 

`UUIDhistory("657e1896-01c2-4e91-a0a1-aa112a382e43")`

Output:

```
uuid version file_change release_date data_release
657e1896-01c2-4e91-a0a1-aa112a382e43       1    released   2018-08-23         12.0
```

Your assistance in resolving this issue is greatly appreciated!

**Comment by LiNk-NY** [comment]
Hi @Sarigenes 

I wasn't able to reproduce the error with Bioconductor 3.18 or 3.19. 
You may be looking for legacy files that no longer exist in the GDC. 

I don't remember when the `legacy` argument was defunct but it looks like you may have an old Bioconductor installation.
Given that this package and `GenomicDataCommons` use APIs, it is strongly recommended that you update your installation. You should be using Bioconductor version 3.18 or greater. 

Best regards,
Marcel

**Comment by Sarigenes** [comment]
Hi @LiNk-NY,

Thank you very much for the information, noted well. 

Have a great day ahead.

**Comment by LiNk-NY** [comment]
@Sarigenes 
FWIW, I searched the GDC for these files at e.g., https://portal.gdc.cancer.gov/v1/files/11b29aeb-57c7-48dd-b2fc-3190d4ea4d39 and it looks like they were removed and no information is provided.
