### ISSUE TITLE
TCGAtranslateID not working?

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/TCGAutils#4]
Shoot, has TCGA really taken down their REST interface to translate UUIDs and broken `TCGAtranslateID`?  e.g.:

```
> TCGAtranslateID("00655296-ce38-4607-a99c-cb9217495e21")
No encoding supplied: defaulting to UTF-8.
Error in if (dim(id_table)[2] == 1L) { : argument is of length zero
```

**Comment by lwaldron** [comment]
Got a helpful response from Bill Wysoki at GDC:

> Regarding the UUID <--> barcode mapping, this feature of the TCGA is no longer functional. However, this can be accomplished in the GDC using the API. See the following link for step-by-step instructions: [https://gdc-docs.nci.nih.gov/API/Users_Guide/Search_and_Retrieval/#example-http-post-request](https://gdc-docs.nci.nih.gov/API/Users_Guide/Search_and_Retrieval/#example-http-post-request).  Running the shell command in the example will output a tab-delimited table that matches each file UUID to a TCGA among other fields that you may require. I am attaching a payload file that will allow you to access this data once you replace the example UUIDs with your own. 

[Payload_ID_name_barcode.example.txt](https://github.com/waldronlab/BiocInterfaces/files/418932/Payload_ID_name_barcode.example.txt)

**Comment by LiNk-NY** [comment]
It seems to me like this can be done through R using the right packages. I'll give it a whirl.

**Comment by LiNk-NY** [comment]
I have added the test function under `/R/TCGAtranslateUUID.R`. I can't get it to work even with a valid JSON request. I could try it with the `RCurl` package.

**Comment by schifferl** [comment]
I will take a look at the JSON request and see if I can make it work too!

**Comment by LiNk-NY** [comment]
It seems like the request only works for certain UUIDs and not others. I was testing the function with UUIDs pulled from files on the GDC website. 
I tried the function again with the UUIDs provided in the example API documentation and those worked. The problem seems to be on their end..

**Comment by lwaldron** [comment]
By the way, their help desk seems to be responsive to requests and bug
reports (support@nci-gdc.datacommons.io)...

**Comment by LiNk-NY** [comment]
Yes indeed, they helped me figure out the reverse translation.
