### ISSUE TITLE
getBroadSubtypes

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/TCGAutils#6]
If you want to make use of the functionality that I've written on getting expression-based subtypes for a specified cancer type - check the `getBroadSubtypes` function in here:

https://github.com/waldronlab/subtypeHeterogeneity/blob/master/R/setup_subtype_clonality.R

Feel free to use/modify/extend it in your way or prompt modifications or in case you would like to init a pull request.

**Comment by LiNk-NY** [comment]
Thanks Ludwig, @lgeistlinger 

This was added to the `RTCGAToolbox` which is good for download all sorts of TCGA data. See it here:
mksamur/RTCGAToolbox@1fd0b0f63087a60b1fc1a32d6b4095275c536e45

Regards,
Marcel
