### ISSUE TITLE
gistic2RangedSummarizedExperiment

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/TCGAutils#7]
If you want to make use of the functionality that I've written on getting the original GISTIC2 calls (not the one already mapped to genes) of specified peak type for a specified cancer type - check the `gistic2RSE` function in here:

https://github.com/waldronlab/subtypeHeterogeneity/blob/master/R/setup_subtype_clonality.R

Feel free to use/modify/extend it in your way or prompt modifications or in case you would like to init a pull request.

**Comment by LiNk-NY** [comment]
Thanks Ludwig! @lgeistlinger 
I will look into these. 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Thanks Ludwig, @lgeistlinger 
I have included this function in the package. See d390e3a1af72d1bfaec648d032d5be7e0d946d19
